name: 'Identity service updater'
description: 'Update subdomains on the cinch-labs identity service'
author: 'cinch-labs'
inputs:
  auth-authority:
    required: true
    description: 'The auth authority you want to update (e.g. https://identity-uat.cinch.co.uk)'
  access-key:
    required: true
    description: 'The access key for the identity service you want to update'
  subdomain-infix:
    required: true
    description: 'The cinch subdomain prefix you want to update the identity service with'
  update-type:
    required: false
    default: 'add'
    description: 'The type of update you want to initiate (e.g. "add" or "delete")'
runs:
  using: 'node12'
  main: 'dist/index.js'
