name: 'Build & Test'

on:
  pull_request:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cinch-labs'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
      - run: npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          auth-authority: https://identity-uat.cinch.co.uk
          access-key: 1234
          subdomain-infix: sheep
